(function(){
  var k='forja_cookie_ok';
  try { if (localStorage.getItem(k)) return; } catch(e) {}
  var s=document.createElement('style'); s.textContent=":root{--surface:#FFFFFF;--line:#D5DBE6;--fg:#151B26;--muted:#566074;--ember:#E8530E;--ember-ink:#FFFFFF;--gutter:16px}@media (prefers-color-scheme:dark){:root:not([data-theme=\"light\"]){--surface:#1A2030;--line:#2B3447;--fg:#EEF1F7;--muted:#9AA5BA;--ember:#FF8A3D;--ember-ink:#1A1209}}:root[data-theme=\"dark\"]{--surface:#1A2030;--line:#2B3447;--fg:#EEF1F7;--muted:#9AA5BA;--ember:#FF8A3D;--ember-ink:#1A1209}\n.ck { position:fixed; left:var(--gutter); right:var(--gutter); bottom:calc(var(--gutter) + env(safe-area-inset-bottom,0px)); max-width:620px; margin-inline:auto; background:var(--surface); color:var(--fg); border:1px solid var(--line); border-radius:12px; padding:16px; display:flex; gap:14px; align-items:center; flex-wrap:wrap; box-shadow:0 10px 30px rgba(0,0,0,.25); z-index:50; font-size:14px; }\n.ck p { margin:0; flex:1 1 240px; color:var(--muted); }\n.ck a { color:var(--fg); }\n.ck button { font:inherit; font-weight:700; background:var(--ember); color:var(--ember-ink); border:0; border-radius:8px; padding:10px 18px; cursor:pointer; }"; document.head.appendChild(s);
  var d=document.createElement('div'); d.className='ck'; d.setAttribute('role','region'); d.setAttribute('aria-label','Aviso de cookies');
  d.innerHTML='<p>Usamos cookies para o site funcionar e, quando houver anúncios, para exibir publicidade do Google. Veja os detalhes na <a href="/privacidade.html">Política de Privacidade</a>.</p><button type="button" id="ck-ok">Entendi</button>';
  document.body.appendChild(d);
  document.getElementById('ck-ok').addEventListener('click',function(){ try{localStorage.setItem(k,'1');}catch(e){} d.remove(); });
})();
